### ISSUE TITLE
새 농구장 추가 API 요청 시 500 에러

### ISSUE THREAD

**Issue by limkhl** [slamapp/frontend#100]
![image (4)](https://user-images.githubusercontent.com/84858773/153744732-b70bad60-01c8-458c-a79f-805ed991bfc8.png)
![image-2](https://user-images.githubusercontent.com/84858773/153744726-6be6b3f9-2c9b-4f11-a8c9-a58a5b9db375.png)
![image-1](https://user-images.githubusercontent.com/84858773/153744730-802e191b-0cfc-424c-a225-f5766f6e4912.png)

**Comment by manudeli** [comment]
@KwonYeKyeong 예경님과 해결하기로 했습니다
