### ISSUE TITLE
withSuspense 문제 (hoc가 Next.js Fast Refresh를 어렵게 함)

### ISSUE THREAD

**Issue by manudeli** [slamapp/frontend#259]
https://nextjs.org/docs/basic-features/fast-refresh#limitations

**Comment by ChanhyukPark-Tech** [comment]
정말 좋은 시각 주셔서 감사합니다.
본 레포지토리의 `withSuspense` 에 대해 많은 영감을 얻었는데 이러한 이슈가 있었네요..

실제 더미 프로젝트를 만들어서 테스트를 해보니 개발시 state가 초기화 되네요.
두 가지 질문이 있는데 가능하면 답변 부탁드리고 싶습니다!

첫번째 질문) `fast refresh` 가 개발환경에서의 편의성을 위한 것이므로 `Production` 시에는 `withSuspense` hoc을 유지하여도 상관이없을까요? 결국 개발자 경험을 저하시키는것 뿐인가요?

두번째 질문) 올려주신 링크에서 다음과 같은 문구가 있습니다.
>Sometimes, a file would export the result of calling a higher-order component like HOC(WrappedComponent). If the returned component is a class, its state will be reset.

저는 hoc를 사용해도, 결국은 NextPage를 리턴하도록 되어있고 `withSuspense` 의 첫번째 인자로 함수를 이용하여 functional component를 리턴해주므로 구조만 hoc이지만, class component 가 아닌 functional component 를 반환하므로 상태가 리셋되지 않을 줄 알았습니다. 타입이 NextPage이고 이것이 Class, Functional을 둘다 내포하고 있기 떄문일까요?

다시 한번 좋은 이슈해결해주셔서 감사합니다!

**Comment by manudeli** [comment]
> @manudeli 님  정말 좋은 시각 주셔서 감사합니다.
> 본 레포지토리의 `withSuspense` 에 대해 많은 영감을 얻었는데 이러한 이슈가 있었네요..
> 
> 실제 더미 프로젝트를 만들어서 테스트를 해보니 개발시 state가 초기화 되네요.
> 두 가지 질문이 있는데 가능하면 답변 부탁드리고 싶습니다!
> 
> 첫번째 질문) `fast refresh` 가 개발환경에서의 편의성을 위한 것이므로 `Production` 시에는 `withSuspense` hoc을 유지하여도 상관이없을까요? 결국 개발자 경험을 저하시키는것 뿐인가요?
> 
> 두번째 질문) 올려주신 링크에서 다음과 같은 문구가 있습니다.
> >Sometimes, a file would export the result of calling a higher-order component like HOC(WrappedComponent). If the returned component is a class, its state will be reset.
> 
> 저는 hoc를 사용해도, 결국은 NextPage를 리턴하도록 되어있고 `withSuspense` 의 첫번째 인자로 함수를 이용하여 functional component를 리턴해주므로 구조만 hoc이지만, class component 가 아닌 functional component 를 반환하므로 상태가 리셋되지 않을 줄 알았습니다. 타입이 NextPage이고 이것이 Class, Functional을 둘다 내포하고 있기 떄문일까요?
> 
> 다시 한번 좋은 이슈해결해주셔서 감사합니다!

오 그러게요 다시 읽어보니 이름없는 함수의 경우라고 쓰여있는데 이름을 넣어주면 되는지 한번 테스트해봐야겠는걸요

제가 한 withSuspense에서는 이름없는 함수를 리턴했으니 이름을 붙여주면 될까요? 덕분에 이슈 한번 다시 오픈합니다

![Screenshot_20221117_185204_GitHub.jpg](https://user-images.githubusercontent.com/61593290/202414413-6532f22f-8164-4b56-9f82-e3149b175c46.jpg)

withResetBoundary등 기존에 많이 보이는 패턴인데 제가 속단한 게 아닌가 싶네요

이름붙여서 다시 테스트해봐야겠어요

**Comment by manudeli** [comment]
> @manudeli 님  정말 좋은 시각 주셔서 감사합니다.
> 본 레포지토리의 `withSuspense` 에 대해 많은 영감을 얻었는데 이러한 이슈가 있었네요..
> 
> 실제 더미 프로젝트를 만들어서 테스트를 해보니 개발시 state가 초기화 되네요.
> 두 가지 질문이 있는데 가능하면 답변 부탁드리고 싶습니다!
> 
> 첫번째 질문) `fast refresh` 가 개발환경에서의 편의성을 위한 것이므로 `Production` 시에는 `withSuspense` hoc을 유지하여도 상관이없을까요? 결국 개발자 경험을 저하시키는것 뿐인가요?
> 
> 두번째 질문) 올려주신 링크에서 다음과 같은 문구가 있습니다.
> >Sometimes, a file would export the result of calling a higher-order component like HOC(WrappedComponent). If the returned component is a class, its state will be reset.
> 
> 저는 hoc를 사용해도, 결국은 NextPage를 리턴하도록 되어있고 `withSuspense` 의 첫번째 인자로 함수를 이용하여 functional component를 리턴해주므로 구조만 hoc이지만, class component 가 아닌 functional component 를 반환하므로 상태가 리셋되지 않을 줄 알았습니다. 타입이 NextPage이고 이것이 Class, Functional을 둘다 내포하고 있기 떄문일까요?
> 
> 다시 한번 좋은 이슈해결해주셔서 감사합니다!

오 그러게요 다시 읽어보니 이름없는 함수의 경우라고 쓰여있는데 이름을 넣어주면 되는지 한번 테스트해봐야겠는걸요

제가 한 withSuspense에서는 이름없는 함수를 리턴했으니 이름을 붙여주면 될까요? 덕분에 이슈 한번 다시 오픈합니다

![Screenshot_20221117_185204_GitHub.jpg](https://user-images.githubusercontent.com/61593290/202414413-6532f22f-8164-4b56-9f82-e3149b175c46.jpg)

withResetBoundary등 기존에 많이 보이는 패턴인데 제가 속단한 게 아닌가 싶네요

이름붙여서 다시 테스트해봐야겠어요

**Comment by ChanhyukPark-Tech** [comment]
```tsx
const withSuspense: WithSuspense = (
  Component,
  Fallback = (
    <Flex.Center>
      <Text _fontSize={24}>기본 로딩 컴포넌트</Text>
    </Flex.Center>
  )
) => {
  const foo = (props: any) => {
    return (
      <SSRSafeSuspense
        fallback={
          typeof Fallback === "function" ? <Fallback {...props} /> : Fallback
        }
      >
        <Component {...props} />
      </SSRSafeSuspense>
    );
  };

  return foo;
};
```

위 방식처럼 해봤는데도 HMR시에 State 가 reset 되네요..ㅠ 

withSuspense를 사용하는 부분에서 첫번째 인자로 익명함수가 들어가는것 자체가 문제일까요..

```tsx
const Poo = withSuspense(() => {
  ...
})
```

**Comment by manudeli** [comment]
@ChanhyukPark-Tech 찬혁님, 이 이슈 해결했습니다.ㅎㅎ
찬혁님이 말씀주셔서 이슈 reopen시켜주신 덕분에 해결할 수 있었네요. 감사합니다👍

## 1. Add withSuspense in @suspensive/react 1.6.1
Fast Refresh가 가능한 Suspense hoc를 @suspensive/react 1.6.1 버전에서 해결해서 withSuspense 추가했어요. 이 withSuspense를 https://github.com/slamapp/frontend/commit/6be1e717e18b42e3f89e01b557a8aa66ce1f5b60에서 사용했는데요.

하지만 사용법은  위 커밋을 참고하시면 볼 수 있는데요. 문제는 함수를 직접사용하지 않고 따로 나눠서 사용하면 가능하더라구요.


## 2. How to use fast refresh with hoc

### GOOD to fast refresh
```tsx
const Contents = withSuspense.CSROnly(Suspended, { fallback: <Fallback /> })
function Suspended() {
  // something suspended Component
}
```

### BAD to fast refresh
```tsx
const Contents = withSuspense.CSROnly(Suspended() {
  // something suspended Component
}, { fallback: <Fallback /> })
```

**Comment by ChanhyukPark-Tech** [comment]
오오 좋은 정보 감사합니다! 
참고해서 저도 적용해봐야겠네요..대박!

**Comment by manudeli** [comment]
@all-contributers please add @ChanhyukPark-Tech for bug

**Comment by manudeli** [comment]
@all-contributors please add @ChanhyukPark-Tech for bug
